### ISSUE TITLE
доделать кнопки на первой странице 

### ISSUE THREAD

**Issue by sonia13marker** [sonia13marker/our_team_project#16]
нужно доделать кнопки смены языка и тем на первой странице, их сейчас там нет в принципе. 
![image](https://user-images.githubusercontent.com/111881249/207665194-d234fd5e-2cf1-489b-a080-8cae1e081563.png)

**Comment by NailGilmanov** [comment]
Готово

**Comment by sonia13marker** [comment]
молодец, кнопки доделаны. ждем, когда будут работать и переключаться )
