### ISSUE TITLE
реализовать анимацию на второй странице

### ISSUE THREAD

**Issue by sonia13marker** [sonia13marker/our_team_project#18]
реализовать анимацию при наведении на блоки с картинками в разделе "команда". подробная информация в макете в фигме.
![image](https://user-images.githubusercontent.com/111881249/207665912-4ace0844-e907-44e3-83ce-635b7ce75c4a.png)

**Comment by NailGilmanov** [comment]
Готово, но от части

**Comment by sonia13marker** [comment]
![Image](https://user-images.githubusercontent.com/111881249/208532898-c7fa78b9-45fc-43ce-9428-2b50d39b820b.png)



анимация реализована, вынесены правки, что надо доделать
