### ISSUE TITLE
реализовать анимацию на второй странице 2

### ISSUE THREAD

**Issue by sonia13marker** [sonia13marker/our_team_project#19]
нужно реализовать анимацию либо при наведении, либо при прокрутке у раздела "наши качества". подробную информацию можно увидеть в макете или узнать у меня.
![image](https://user-images.githubusercontent.com/111881249/207666296-931fda51-5237-496b-9c7f-9f4142d7b4d1.png)

**Comment by NailGilmanov** [comment]
Готово

**Comment by sonia13marker** [comment]
проверить завтра, работает или нет

**Comment by NailGilmanov** [comment]
Проверишь у себя, но теперь точно должно работать

**Comment by NailGilmanov** [comment]
и самое приятное - Готово

**Comment by sonia13marker** [comment]
супер, работает! думаю можно поработать над плавностью, если успею/смогу, то что-нибудь сделаю;)

![Image](https://user-images.githubusercontent.com/111881249/208963869-4e49cfa5-5277-4ede-a772-532a421e6870.png)
