### ISSUE TITLE
реализовать кнопку "посмотреть еще" в проектах

### ISSUE THREAD

**Issue by sonia13marker** [sonia13marker/our_team_project#42]
сжать проекты до 4 отображаемых по дефолту и добавить кнопку "показать еще", т.е. сделать первую версию из макета.
![image](https://user-images.githubusercontent.com/111881249/208268958-32fa862d-0eba-45be-a03f-099b209f1b22.png)

**Comment by sonia13marker** [comment]
https://ru.stackoverflow.com/questions/1207573/Подгрузка-контента-через-кнопку-Показать-еще 
возможно это поможет

**Comment by x64penguin** [comment]
давай отложим это, есть задания по важней, серьезно, это не так важно

**Comment by sonia13marker** [comment]
окей, тогда сделай другое

**Comment by sonia13marker** [comment]
кнопка сделала, все работает
![Image](https://user-images.githubusercontent.com/111881249/208759748-a1d052e3-7839-44b1-a10e-c275f725f4a8.png)
